spring.application.name=site-service



spring.datasource.url=jdbc:mysql://localhost:3306/drone
spring.datasource.username=root
spring.datasource.password=Krishnani@7634
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.hibernate.ddl-auto=update

server.port=${PORT:0}
eureka.client.serviceUrl.defaultZone = http://localhost:8010/eureka
service.devtool.restart.enable=true


#with the  help  of  this   we  can    register on   e8ureka  with  instace name
# and  the  random  value  for   running multiple  instaces
eureka.instance.instanceId=${spring.application.name}:${spring.application.instance.id:${random.value}}

